"""Add registered_via_link_id to User model

Revision ID: 0d901cb6ee51
Revises: 7e83b9107fcc
Create Date: 2025-05-27 16:45:34.292216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d901cb6ee51'
down_revision = '7e83b9107fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_via_link_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'registration_links', ['registered_via_link_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('registered_via_link_id')

    # ### end Alembic commands ###
