"""Add RegistrationLink model and update User model timestamps

Revision ID: 667fbb38e0b7
Revises: 6ffd62624c3f
Create Date: 2025-05-23 01:30:23.308981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667fbb38e0b7'
down_revision = '6ffd62624c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('custom_path', sa.String(length=100), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('default_permission', sa.String(length=50), nullable=False),
    sa.Column('auto_enable_new_users', sa.Boolean(), nullable=False),
    sa.Column('fixed_username', sa.String(length=80), nullable=True),
    sa.Column('fixed_email', sa.String(length=120), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_path'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_links')
    # ### end Alembic commands ###
