"""add description to post_processes

Revision ID: 73abed0cd67c
Revises: 0d901cb6ee51
Create Date: 2025-05-27 18:57:06.762876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73abed0cd67c'
down_revision = '0d901cb6ee51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('machines', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('machines', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('post_processes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('post_processes', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.add_column('post_processes', sa.Column('cost_per_hour', sa.Float(), nullable=True))
    op.add_column('post_processes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_processes', 'is_active')
    op.drop_column('post_processes', 'cost_per_hour')
    op.drop_column('post_processes', 'estimated_time')
    op.drop_column('post_processes', 'description')
    op.drop_column('machines', 'is_active')
    op.drop_column('machines', 'location')
    op.drop_column('machines', 'description')
    # ### end Alembic commands ###
