"""Update User and Part models, implement RBAC and new part numbering

Revision ID: d33ef37d74fa
Revises: 4145c9fad8be
Create Date: 2025-05-22 19:19:55.903314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd33ef37d74fa'
down_revision = '4145c9fad8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_material', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('have_material', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('quantity_required', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cut_length', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('drawing_created', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('enabled')
        batch_op.drop_column('permission')

    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('drawing_created')
        batch_op.drop_column('priority')
        batch_op.drop_column('cut_length')
        batch_op.drop_column('quantity_required')
        batch_op.drop_column('have_material')
        batch_op.drop_column('source_material')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
